modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="EtSH_C2H6S"
description='A tconstruct addon that add supports and integration for AnvilCraft mod.'

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
modId="tconstruct"
mandatory=true
versionRange="[3.9.1.23,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="anvilcraft"
mandatory=true
versionRange="[1.4.0,)"
ordering="AFTER"
side="BOTH"